export const SIDEBAROPEN = `SIDEBAROPEN`;
export const SIDEBARCLOSE = `SIDEBARCLOSE`;
export const GET_PRODUCTS_BEGIN = `GETPRODUCTSBEGIN`;
export const GET_PRODUCT_SUCCESS = `GETPRODUCTSUCCESS`;
export const GET_PRODUCT_ERROR = `GETPRODUCTSERROR`;
export const GET__SINGLE_PRODUCTS_BEGIN = `GETSINGLEPRODUCTSBEGIN`;
export const GET__SINGLE_PRODUCT_SUCCESS = `GETSINGLEPRODUCTSUCCESS`;
export const GET__SINGLE_PRODUCT_ERROR = `GETSINGLEPRODUCTERROR`;

// Filter Products 
export const LOAD_PRODUCT = `LOADPRODUCT`;
export const SET_GRIDVIEW= `SETGRIDVIEW`;
export const SET_LISTVIEW = `SETLISTVIEW`;
export const UPDATE_SORT = `UPDATESORT`;
export const SORT_PRODUCTS = `SORTPRODUCT`;
export const UPDATE_FILTERS = `UPDATEFILTERS`;
export const FILTERS_PRODUCTS = `FILTERSPRODUCTS`;
export const CLEAR_FILTERS = `CLEARFILTERS`;

// For Cart
export const ADD_TO_CART = `ADDTOCART`;
export const REMOVE_CART_ITEM = `REMOVECARTITEM`;
export const CLEAR_CART = `CLEARCART`;
export const ADD_TO_TOGGLE_AMOUNT = `ADDTOTOGGLEAMOUNT`;
export const COUNT_CART_TOTALS = `COUNTCARTTOTALS`;




